[package]
name = "tiralabra"
version = "0.1.0"
authors = ["Roope Salmi <rpsalmi@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
rand = { version = "0.8", default-features = false, features = ["std", "small_rng"] }

[features]

